### ISSUE TITLE
子菜单刷新还是会跳转去首页

### ISSUE THREAD

**Issue by lithromantic-Fish** [Nirongxu/vue-xuAdmin#1]

**Comment by lithromantic-Fish** [comment]
next('index')改成next({path:to.fullPath})是不是好点？

**Comment by Nirongxu** [comment]
> l

这样也可以，根据自己的需要，可以选择刷新显示当前子路由还是返回主页

**Comment by Nirongxu** [comment]
> 下（ '索引'）改成下（{路径：to.fullPath}）是不是好点？

这样也可以，根据自己的需要，可以选择刷新显示当前子路由还是返回主页

**Comment by xuxuxu-ni** [comment]
> next('index')改成next({path:to.fullPath})是不是好点？

这样也可以，根据自己的需要，可以选择刷新显示当前子路由还是返回主页

**Comment by kxilong** [comment]
这种做法好像并没有用啊？怎么解决

**Comment by huangshizhan** [comment]
线上demo没看到 路由权限管理啊？

**Comment by xuxuxu-ni** [comment]
有的,通过选择对应的权限,可以查看左侧的对应菜单变化,并且也可以在"按钮权限"页面看到对应的权限按钮,线上demo部署在github上面可能存在加载问题,建议刷新几遍,或者下载到本地运行一下,帮忙点个star,谢谢





------------------ 原始邮件 ------------------
发件人: "huangshizhan"<notifications@github.com>;
发送时间: 2019年9月29日(星期天) 下午4:53
收件人: "Nirongxu/vue-xuAdmin"<vue-xuAdmin@noreply.github.com>;
抄送: "倪荣旭"<595485548@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [Nirongxu/vue-xuAdmin] 子菜单刷新还是会跳转去首页 (#1)




线上demo没看到 路由权限管理啊？

**Comment by huangshizhan** [comment]
我的意思是这张图上面的给角色分配路由权限，麻烦看看
![image](https://user-images.githubusercontent.com/26118170/65830113-fd316280-e2de-11e9-8340-d6342be3da18.png)

**Comment by huangshizhan** [comment]
> 有的,通过选择对应的权限,可以查看左侧的对应菜单变化,并且也可以在"按钮权限"页面看到对应的权限按钮,线上demo部署在github上面可能存在加载问题,建议刷新几遍,或者下载到本地运行一下,帮忙点个star,谢谢
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "huangshizhan"<notifications@github.com>; 发送时间: 2019年9月29日(星期天) 下午4:53 收件人: "Nirongxu/vue-xuAdmin"<vue-xuAdmin@noreply.github.com>; 抄送: "倪荣旭"<595485548@qq.com>;"Comment"<comment@noreply.github.com>; 主题: Re: [Nirongxu/vue-xuAdmin] 子菜单刷新还是会跳转去首页 (#1) 线上demo没看到 路由权限管理啊？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.
我的意思是这张图上面的给角色分配路由权限，麻烦看看
![image](https://user-images.githubusercontent.com/26118170/65830132-2e119780-e2df-11e9-995f-9a934a0c4f8a.png)

**Comment by xuxuxu-ni** [comment]
这是我的另外一个的开源项目,是一个全栈项目,后台使用的是node.js,项目地址:https://github.com/Nirongxu/nodePlatform-eggjs,要达到可配置的权限路由的话必须是需要后台支持的




------------------ 原始邮件 ------------------
发件人: "huangshizhan"<notifications@github.com>;
发送时间: 2019年9月29日(星期天) 下午5:33
收件人: "Nirongxu/vue-xuAdmin"<vue-xuAdmin@noreply.github.com>;
抄送: "倪荣旭"<595485548@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [Nirongxu/vue-xuAdmin] 子菜单刷新还是会跳转去首页 (#1)



 
有的,通过选择对应的权限,可以查看左侧的对应菜单变化,并且也可以在"按钮权限"页面看到对应的权限按钮,线上demo部署在github上面可能存在加载问题,建议刷新几遍,或者下载到本地运行一下,帮忙点个star,谢谢
 …
 ------------------ 原始邮件 ------------------ 发件人: "huangshizhan"notifications@github.com; 发送时间: 2019年9月29日(星期天) 下午4:53 收件人: "Nirongxu/vue-xuAdmin"vue-xuAdmin@noreply.github.com; 抄送: "倪荣旭"595485548@qq.com;"Comment"comment@noreply.github.com; 主题: Re: [Nirongxu/vue-xuAdmin] 子菜单刷新还是会跳转去首页 (#1) 线上demo没看到 路由权限管理啊？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.
 我的意思是这张图上面的给角色分配路由权限，麻烦看看

**Comment by huangshizhan** [comment]
> 这是我的另外一个的开源项目,是一个全栈项目,后台使用的是node.js,项目地址:[https://github.com/Nirongxu/nodePlatform-eggjs,要达到可配置的权限路由的话必须是需要后台支持的](https://github.com/Nirongxu/nodePlatform-eggjs,%E8%A6%81%E8%BE%BE%E5%88%B0%E5%8F%AF%E9%85%8D%E7%BD%AE%E7%9A%84%E6%9D%83%E9%99%90%E8%B7%AF%E7%94%B1%E7%9A%84%E8%AF%9D%E5%BF%85%E9%A1%BB%E6%98%AF%E9%9C%80%E8%A6%81%E5%90%8E%E5%8F%B0%E6%94%AF%E6%8C%81%E7%9A%84)
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "huangshizhan"<notifications@github.com>; 发送时间: 2019年9月29日(星期天) 下午5:33 收件人: "Nirongxu/vue-xuAdmin"<vue-xuAdmin@noreply.github.com>; 抄送: "倪荣旭"<595485548@qq.com>;"Comment"<comment@noreply.github.com>; 主题: Re: [Nirongxu/vue-xuAdmin] 子菜单刷新还是会跳转去首页 (#1) 有的,通过选择对应的权限,可以查看左侧的对应菜单变化,并且也可以在"按钮权限"页面看到对应的权限按钮,线上demo部署在github上面可能存在加载问题,建议刷新几遍,或者下载到本地运行一下,帮忙点个star,谢谢 … ------------------ 原始邮件 ------------------ 发件人: "huangshizhan"notifications@github.com; 发送时间: 2019年9月29日(星期天) 下午4:53 收件人: "Nirongxu/vue-xuAdmin"vue-xuAdmin@noreply.github.com; 抄送: "倪荣旭"595485548@qq.com;"Comment"comment@noreply.github.com; 主题: Re: [Nirongxu/vue-xuAdmin] 子菜单刷新还是会跳转去首页 (#1) 线上demo没看到 路由权限管理啊？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread. 我的意思是这张图上面的给角色分配路由权限，麻烦看看 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

可以加个微信或者qq吗（1666385820 微信QQ同号）

**Comment by xuxuxu-ni** [comment]
上个版本已经实现这个功能了
